name: tests

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        toolchain:
          #- stable .. until llvm-cov in llvm-tools (1.49)
          - nightly
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
        profile: minimal
        components: llvm-tools-preview

    - uses: actions-rs/install@v0.1
      with:
        crate: rustfilt
        version: latest

    - name: Tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --no-fail-fast
# vim: set ts=2 sts=2 sw=2:
